from PySide6 import QtCore, QtWidgets, QtGui, QtNetwork
from PySide6.QtWidgets import QSizePolicy

# FFT Peaks (Sweep)
class SweepFFTControlWidget(QtWidgets.QWidget):
    def __init__(self, parent=None):
        super().__init__(parent=parent)
        self.frame_base = QtWidgets.QFrame(self)
        # self.frame_base.setStyleSheet("QFrame { border: 3px solid red; }")
        self.frame_base.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        self.controls_layout = QtWidgets.QGridLayout(self.frame_base)
        self.controls_antSelect_group = QtWidgets.QGroupBox("Antenna")
        self.controls_antSelect_group.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        self.controls_layout.addWidget(self.controls_antSelect_group, 0, 0)
        self.controls_antSelect_layout = QtWidgets.QVBoxLayout(self.controls_antSelect_group)
        self.controls_antSelect_tx = QtWidgets.QRadioButton("Transmitter")
        self.controls_antSelect_tx.setChecked(True)
        self.controls_antSelect_rx = QtWidgets.QRadioButton("Receiver")
        self.controls_antSelect_layout.addWidget(self.controls_antSelect_tx)
        self.controls_antSelect_layout.addWidget(self.controls_antSelect_rx)

        self.controls_az_group = QtWidgets.QGroupBox("Azimuth")
        self.controls_layout.addWidget(self.controls_az_group, 1, 0)
        self.controls_az_layout = QtWidgets.QVBoxLayout(self.controls_az_group)
        self.controls_az_start_frame = QtWidgets.QFrame()
        self.controls_az_layout.addWidget(self.controls_az_start_frame)
        self.controls_az_stop_frame = QtWidgets.QFrame()
        self.controls_az_layout.addWidget(self.controls_az_stop_frame)
        self.controls_az_step_frame = QtWidgets.QFrame()
        self.controls_az_layout.addWidget(self.controls_az_step_frame)
        self.controls_az_start_layout = QtWidgets.QHBoxLayout(self.controls_az_start_frame)
        self.controls_az_start_label = QtWidgets.QLabel("Start")
        self.controls_az_start_layout.addWidget(self.controls_az_start_label)
        self.controls_az_start_text = QtWidgets.QLineEdit(text="-1.0")
        self.controls_az_start_layout.addWidget(self.controls_az_start_text)
        self.controls_az_stop_layout = QtWidgets.QHBoxLayout(self.controls_az_stop_frame)
        self.controls_az_stop_label = QtWidgets.QLabel("Stop")
        self.controls_az_stop_layout.addWidget(self.controls_az_stop_label)
        self.controls_az_stop_text = QtWidgets.QLineEdit(text="1.0")
        self.controls_az_stop_layout.addWidget(self.controls_az_stop_text)
        self.controls_az_step_layout = QtWidgets.QHBoxLayout(self.controls_az_step_frame)
        self.controls_az_step_label = QtWidgets.QLabel("Step")
        self.controls_az_step_layout.addWidget(self.controls_az_step_label)
        self.controls_az_step_text = QtWidgets.QLineEdit(text="1.0")
        self.controls_az_step_layout.addWidget(self.controls_az_step_text)

        self.controls_el_group = QtWidgets.QGroupBox("Elevation")
        self.controls_layout.addWidget(self.controls_el_group, 1, 1)
        self.controls_el_layout = QtWidgets.QVBoxLayout(self.controls_el_group)
        self.controls_el_start_frame = QtWidgets.QFrame()
        self.controls_el_layout.addWidget(self.controls_el_start_frame)
        self.controls_el_stop_frame = QtWidgets.QFrame()
        self.controls_el_layout.addWidget(self.controls_el_stop_frame)
        self.controls_el_step_frame = QtWidgets.QFrame()
        self.controls_el_layout.addWidget(self.controls_el_step_frame)
        self.controls_el_start_layout = QtWidgets.QHBoxLayout(self.controls_el_start_frame)
        self.controls_el_start_label = QtWidgets.QLabel("Start")
        self.controls_el_start_layout.addWidget(self.controls_el_start_label)
        self.controls_el_start_text = QtWidgets.QLineEdit(text="-1.0")
        self.controls_el_start_layout.addWidget(self.controls_el_start_text)
        self.controls_el_stop_layout = QtWidgets.QHBoxLayout(self.controls_el_stop_frame)
        self.controls_el_stop_label = QtWidgets.QLabel("Stop")
        self.controls_el_stop_layout.addWidget(self.controls_el_stop_label)
        self.controls_el_stop_text = QtWidgets.QLineEdit(text="1.0")
        # self.controls_el_stop_text.setSizeHint()
        self.controls_el_stop_layout.addWidget(self.controls_el_stop_text)
        self.controls_el_step_layout = QtWidgets.QHBoxLayout(self.controls_el_step_frame)
        self.controls_el_step_label = QtWidgets.QLabel("Step")
        self.controls_el_step_layout.addWidget(self.controls_el_step_label)
        self.controls_el_step_text = QtWidgets.QLineEdit(text="1.0")
        self.controls_el_step_layout.addWidget(self.controls_el_step_text)

        self.controls_sweepType_group = QtWidgets.QGroupBox("Sweep Type")
        self.controls_layout.addWidget(self.controls_sweepType_group, 0, 1)
        self.controls_sweepType_layout = QtWidgets.QVBoxLayout(self.controls_sweepType_group)
        self.controls_sweepType_serpentine = QtWidgets.QRadioButton("Serpentine")
        self.controls_sweepType_serpentine.setChecked(True)
        self.controls_sweepType_grid = QtWidgets.QRadioButton("Grid")
        self.controls_sweepType_layout.addWidget(self.controls_sweepType_serpentine)
        self.controls_sweepType_layout.addWidget(self.controls_sweepType_grid)

# Waveform
class WaveformControlWidget(QtWidgets.QWidget):
    def __init__(self,parent=None):
        super().__init__(parent=parent)
        self.label = QtWidgets.QLabel("Not yet implemented...", self)

# FFT Peaks (Stationary)
class StillFFTControlWidget(QtWidgets.QWidget):
    def __init__(self,parent=None):
        super().__init__(parent=parent)
        self.label = QtWidgets.QLabel("Not yet implemented...", self)

# Jitter (Both Ends)
class JitterBothEndsControlWidget(QtWidgets.QWidget):
    def __init__(self,parent=None):
        super().__init__(parent=parent)
        self.base_frame = QtWidgets.QFrame(self)
        self.base_layout = QtWidgets.QVBoxLayout(self.base_frame)
        self.duration_frame = QtWidgets.QFrame()
        self.base_layout.addWidget(self.duration_frame)
        self.duration_layout = QtWidgets.QHBoxLayout(self.duration_frame)
        self.duration_label = QtWidgets.QLabel("Duration (Seconds):")
        self.duration_spinbox = QtWidgets.QDoubleSpinBox()
        self.duration_layout.addWidget(self.duration_label)
        self.duration_layout.addWidget(self.duration_spinbox)

# Jitter (Single End)
class JitterSingleEndControlWidget(QtWidgets.QWidget):
    def __init__(self,parent=None):
        super().__init__(parent=parent)
        self.label = QtWidgets.QLabel("Not yet implemented...", self)
